import { designFromFeatures, SHOWCASE_BRIEFS } from "@tell/design-skills";

export const dynamic = "force-static";

/** Refined-story educational / docs showcase generated by the skill graph. */
export default function EducationalShowcasePage() {
  const { previewHtml } = designFromFeatures(SHOWCASE_BRIEFS.educational!);
  return (
    <main data-testid="showcase-educational">
      <iframe
        title="Educational docs showcase"
        srcDoc={previewHtml}
        className="h-screen w-full border-0"
        data-testid="showcase-frame"
      />
    </main>
  );
}
