import { ArtDirection } from "@tell/schema";

export const DIRECTION_PRESETS = {
  editorial: {
    id: "editorial-warm",
    label: "Editorial warm",
    keywords: ["warm", "editorial", "less shadow", "serif"],
    tokenOverrides: {
      "--font-display": "Instrument Serif",
      "--accent": "#D4714A",
      "--radius-card": "16px",
      "--shadow-card": "0 2px 8px rgba(0,0,0,.25)",
    },
    summary: "Warm paper tones, serif headlines, restrained depth.",
  },
  precision: {
    id: "precision-instrument",
    label: "Precision instrument",
    keywords: ["precise", "instrument", "measured", "mono"],
    tokenOverrides: {
      "--font-display": "IBM Plex Mono",
      "--accent": "#C4A035",
      "--radius-card": "4px",
      "--shadow-card": "none",
    },
    summary: "Measured spacing, sharper radius, data-forward surfaces.",
  },
  "warm-minimal": {
    id: "warm-minimal",
    label: "Warm minimal",
    keywords: ["warm", "minimal", "quiet"],
    tokenOverrides: {
      "--font-display": "Instrument Serif",
      "--accent": "#B85A32",
      "--radius-card": "8px",
      "--shadow-card": "none",
    },
    summary: "Quieter surfaces with one human accent.",
  },
  "bold-contrast": {
    id: "bold-contrast",
    label: "Bold contrast",
    keywords: ["bold", "contrast", "memorable"],
    tokenOverrides: {
      "--font-display": "Instrument Serif",
      "--accent": "#E8926F",
      "--radius-card": "2px",
      "--shadow-card": "0 12px 40px rgba(0,0,0,.45)",
    },
    summary: "Stronger hierarchy and sharper editorial contrast.",
  },
  luxury: {
    id: "classic-luxury",
    label: "Classic luxury",
    keywords: ["luxury", "premium", "refined", "elegant"],
    tokenOverrides: {
      "--font-display": "Playfair Display",
      "--accent": "#6B2C3E",
      "--radius-card": "3px",
      "--shadow-card": "none",
    },
    summary: "Refined ivory surfaces, letterspaced labels, hairline rules.",
  },
  brutalist: {
    id: "brutalist-utility",
    label: "Brutalist utility",
    keywords: ["brutalist", "raw", "utility", "structural", "mono"],
    tokenOverrides: {
      "--font-display": "Archivo",
      "--accent": "#D94F30",
      "--radius-card": "0px",
      "--shadow-card": "none",
    },
    summary: "Ink borders, uppercase type, visible structure.",
  },
  explainer: {
    id: "visual-textbook",
    label: "Visual textbook",
    keywords: [
      "explainer",
      "essay",
      "textbook",
      "education",
      "educational",
      "blog",
      "diagram",
      "illustration",
      "longform",
      "curious",
      "monochrome",
      "how-it-works",
      "interactive",
      "book",
    ],
    tokenOverrides: {
      "--font-display": "Source Serif 4",
      "--accent": "#3D6B8A",
      "--radius-card": "2px",
      "--shadow-card": "none",
    },
    summary: "Book-like reading column, monochrome restraint, illustration-first rhythm.",
  },
} satisfies Record<string, ArtDirection>;
