import Link from "next/link";
import { designFromFeatures, listTemplates, type DesignTemplate } from "@tell/design-skills";
import { SpecimenPreview } from "@/components/showcase/SpecimenPreview";
import "./showcase.css";

export const dynamic = "force-static";
export const metadata = {
  title: "Tell Specimens — Premium design offerings",
  description:
    "Eight research-backed site kinds generated by Tell's design engine — proof sheets, not theme packs.",
};

type OfferingPreview = DesignTemplate & { previewHtml: string; index: string };

function buildOfferings(): OfferingPreview[] {
  return listTemplates().map((t, i) => ({
    ...t,
    previewHtml: designFromFeatures(t.brief).previewHtml,
    index: String(i + 1).padStart(2, "0"),
  }));
}

/** Specimen gallery — cinema reels of craft beats, not nav-strip thumbnails. */
export default function ShowcaseGalleryPage() {
  const offerings = buildOfferings();
  const featured = offerings.find((o) => o.key === "foundry") ?? offerings.find((o) => o.key === "studio") ?? offerings[0]!;
  const rest = offerings.filter((o) => o.key !== featured.key);

  return (
    <div className="sx-root" data-testid="showcase-gallery">
      <div className="sx-grain" aria-hidden="true" />
      <div className="sx-shell">
        <header className="sx-nav">
          <Link className="sx-brand" href="/showcase">
            <span className="sx-brand-mark">Tell</span>
            <span className="sx-brand-meta">Specimens</span>
          </Link>
          <nav className="sx-nav-links" aria-label="Primary">
            <a href="#index">Index</a>
            <Link href="/studio">Studio</Link>
            <Link href="/">Tell Report</Link>
            <Link className="sx-nav-cta" href={`/showcase/${featured.key}`}>
              Open featured
            </Link>
          </nav>
        </header>

        <section className="sx-hero sx-hero-cinema" aria-labelledby="sx-hero-title">
          <div className="sx-hero-copy">
            <p className="sx-kicker">Premium content-custom design</p>
            <h1 id="sx-hero-title" className="sx-display">
              Specimens, not themes
            </h1>
            <p className="sx-lede">
              Each offering is a measured argument on the page. The reel below walks the craft beats —
              claim, figure, stakes — not a cropped browser chrome.
            </p>
            <div className="sx-hero-actions">
              <Link className="sx-nav-cta" href="/studio">
                Generate yours
              </Link>
              <a className="sx-btn-ghost" href="#index">
                Browse the index
              </a>
            </div>
            <ul className="sx-facts">
              <li>{offerings.length} offerings</li>
              <li>Scroll-reel proofs</li>
              <li>Zero auto-apply</li>
            </ul>
          </div>

          <article className="sx-featured" aria-label={`Featured specimen: ${featured.label}`}>
            <div className="sx-featured-label">
              <span>Featured reel</span>
              <span>
                {featured.index} / {String(offerings.length).padStart(2, "0")}
              </span>
            </div>
            <div className="sx-plate">
              <SpecimenPreview
                className="sx-plate-frame"
                title={`${featured.label} preview`}
                html={featured.previewHtml}
                designWidth={1440}
                designHeight={1100}
                mode="cinema"
                prefer="auto"
                testId="showcase-featured-preview"
              />
              <div className="sx-plate-meta">
                <h2>{featured.label}</h2>
                <p>{featured.marketJob}</p>
                <Link href={`/showcase/${featured.key}`}>Open full specimen →</Link>
              </div>
            </div>
          </article>
        </section>

        <section className="sx-index" id="index" aria-labelledby="sx-index-title">
          <div className="sx-index-head">
            <h2 id="sx-index-title">The index</h2>
            <p>Hover a row to scrub its reel. Stills open on the figure beat, not the nav.</p>
          </div>
          <ol className="sx-list">
            {rest.map((o) => (
              <li key={o.key}>
                <Link
                  className="sx-row"
                  href={`/showcase/${o.key}`}
                  data-testid={`showcase-link-${o.key}`}
                >
                  <span className="sx-num" aria-hidden="true">
                    {o.index}
                  </span>
                  <div className="sx-row-copy">
                    <h3>{o.label}</h3>
                    <p className="sx-kind">{o.siteKind}</p>
                  </div>
                  <p className="sx-row-job">{o.marketJob}</p>
                  <SpecimenPreview
                    className="sx-thumb"
                    title={`${o.label} thumbnail`}
                    html={o.previewHtml}
                    designWidth={1440}
                    designHeight={900}
                    mode="still"
                    prefer="figure"
                    decorative
                    testId={`showcase-thumb-${o.key}`}
                  />
                </Link>
              </li>
            ))}
          </ol>
        </section>

        <footer className="sx-foot">
          <p>Deepened by the recursive improve loop · research learnings compound across sessions.</p>
          <p>
            <Link href="/studio">Edit in Studio</Link>
            {" · "}
            <Link href="/">Back to Tell</Link>
          </p>
        </footer>
      </div>
    </div>
  );
}
