import Link from "next/link";
import { designFromFeatures, listTemplates, type DesignTemplate } from "@tell/design-skills";
import "./showcase.css";

export const dynamic = "force-static";
export const metadata = {
  title: "Tell Specimens — Premium design offerings",
  description:
    "Seven research-backed site kinds generated by Tell's design engine — proof sheets, not theme packs.",
};

type OfferingPreview = DesignTemplate & { previewHtml: string; index: string };

function buildOfferings(): OfferingPreview[] {
  return listTemplates().map((t, i) => ({
    ...t,
    previewHtml: designFromFeatures(t.brief).previewHtml,
    index: String(i + 1).padStart(2, "0"),
  }));
}

/** Specimen gallery — one composition that showcases the engine's craft. */
export default function ShowcaseGalleryPage() {
  const offerings = buildOfferings();
  // Lead with the newest craft gap fill so the gallery feels current, not SaaS-default.
  const featured = offerings.find((o) => o.key === "studio") ?? offerings[0]!;
  const rest = offerings.filter((o) => o.key !== featured.key);

  return (
    <div className="sx-root" data-testid="showcase-gallery">
      <div className="sx-grain" aria-hidden="true" />
      <div className="sx-shell">
        <header className="sx-nav">
          <Link className="sx-brand" href="/showcase">
            <span className="sx-brand-mark">Tell</span>
            <span className="sx-brand-meta">Specimens</span>
          </Link>
          <nav className="sx-nav-links" aria-label="Primary">
            <a href="#index">Index</a>
            <Link href="/studio">Studio</Link>
            <Link href="/">Tell Report</Link>
            <Link className="sx-nav-cta" href={`/showcase/${featured.key}`}>
              Open featured
            </Link>
          </nav>
        </header>

        <section className="sx-hero" aria-labelledby="sx-hero-title">
          <div className="sx-hero-copy">
            <p className="sx-kicker">Premium content-custom design</p>
            <h1 id="sx-hero-title" className="sx-display">
              Specimens, not themes
            </h1>
            <p className="sx-lede">
              Seven site kinds measured against an expert corpus — each one a different argument on
              the page, generated from declared features.
            </p>
            <div className="sx-hero-actions">
              <Link className="sx-nav-cta" href="/studio">
                Generate yours
              </Link>
              <a className="sx-btn-ghost" href="#index">
                Browse the index
              </a>
            </div>
            <ul className="sx-facts">
              <li>{offerings.length} offerings</li>
              <li>Research-loop calibrated</li>
              <li>Zero auto-apply</li>
            </ul>
          </div>

          <article className="sx-featured" aria-label={`Featured specimen: ${featured.label}`}>
            <div className="sx-featured-label">
              <span>Featured proof</span>
              <span>{featured.index} / {String(offerings.length).padStart(2, "0")}</span>
            </div>
            <div className="sx-plate">
              <div className="sx-plate-frame">
                <iframe title={`${featured.label} preview`} srcDoc={featured.previewHtml} tabIndex={-1} />
              </div>
              <div className="sx-plate-meta">
                <h2>{featured.label}</h2>
                <p>{featured.marketJob}</p>
                <Link href={`/showcase/${featured.key}`}>Open full specimen →</Link>
              </div>
            </div>
          </article>
        </section>

        <section className="sx-index" id="index" aria-labelledby="sx-index-title">
          <div className="sx-index-head">
            <h2 id="sx-index-title">The index</h2>
            <p>Each row is a measured corridor — not a color theme with a new name.</p>
          </div>
          <ol className="sx-list">
            {rest.map((o) => (
              <li key={o.key}>
                <Link className="sx-row" href={`/showcase/${o.key}`} data-testid={`showcase-link-${o.key}`}>
                  <span className="sx-num" aria-hidden="true">
                    {o.index}
                  </span>
                  <div className="sx-row-copy">
                    <h3>{o.label}</h3>
                    <p className="sx-kind">{o.siteKind}</p>
                  </div>
                  <p className="sx-row-job">{o.marketJob}</p>
                  <div className="sx-thumb" aria-hidden="true">
                    <iframe title="" srcDoc={o.previewHtml} tabIndex={-1} />
                  </div>
                </Link>
              </li>
            ))}
          </ol>
        </section>

        <footer className="sx-foot">
          <p>Deepened by the design-research loop · plumbing floors from peer builders only when stuck.</p>
          <p>
            <Link href="/studio">Edit in Studio</Link>
            {" · "}
            <Link href="/">Back to Tell</Link>
          </p>
        </footer>
      </div>
    </div>
  );
}
