import { designFromFeatures, SHOWCASE_BRIEFS } from "@tell/design-skills";

export const dynamic = "force-static";

/** Conversion-sharp SaaS marketing showcase generated by the skill graph. */
export default function SaasShowcasePage() {
  const { previewHtml } = designFromFeatures(SHOWCASE_BRIEFS.saas!);
  return (
    <main data-testid="showcase-saas">
      <iframe
        title="SaaS marketing showcase"
        srcDoc={previewHtml}
        className="h-screen w-full border-0"
        data-testid="showcase-frame"
      />
    </main>
  );
}
